name: FrankenPress PHP 8.3

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}    

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: notglossy/frankenpress
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
          labels: |
            org.opencontainers.image.title=FrankenPress
            org.opencontainers.image.description=WordPress running on FrankenPHP - a high-performance PHP application server
            org.opencontainers.image.licenses=MIT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/i386,linux/arm/v7
          push: true
          context: .
          tags: |
            notglossy/frankenpress:php-8.3
            ghcr.io/${{ github.repository_owner }}/frankenpress:php-8.3
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=8.3
          labels: ${{ steps.meta.outputs.labels }}
          